modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/wolfieboy09/KubeJS-CC-1.20.1/issues"
license = "LGPLv3"

[[mods]]
modId = "kjscc"
version = "${mod_version}"
displayName = "KubeJS ComputerCraft"
authors = "Wolfieboy09"
description = '''
Adding support for ComputerCraft from KubeJS.
Credit go to Amygdaloideae (Prunoideae on GitHub) for the original mod that I ported from.
'''
logoFile = "icon.png"

[[dependencies.kjscc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjscc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjscc]]
modId = "computercraft"
mandatory = true
ordering = "AFTER"
side = "BOTH"
versionRange = "[*,)"

[[dependencies.kjscc]]
modId = "kubejs"
mandatory = true
ordering = "NONE"
side = "BOTH"
versionRange = "[*,)"